site_name: ckantools

theme:
  name: material
  palette:
    primary: green
    accent: green

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
